### ISSUE TITLE
[question] Is Newpipe illegal? 

### ISSUE THREAD

**Issue by conrad-heimbold** [TeamNewPipe/NewPipeExtractor#10]
According to the terms of service of Google ( https://www.google.com/intl/en/policies/terms/regional.html ) : 
"Don’t misuse our Services. For example, don’t interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. "
- Parsing a website is probably **not** a *provided instruction*. 

Sorr y if this has been already asked, I could not find such an issue.

**Comment by TheAssassin** [comment]
We cannot give a real answer to you here. This is due to the fact that we do not intend to provide any legal advice,. and the following sentences are no such advice, and I hereby state that you cannot hold me liable for any of the following words.

The app itself cannot be illegal, the only thing that might be illegal is the actual usage. Let me give you some details about the legal situation regarding the usage of NewPipe.

First of all, the developers cannot be held liable for anything illegal done with this software, considering the GPL license text:

>   THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

You see, technically the team (including me), the contributors, we are protected by that license. Users could not sue us because they did something illegal with the software, and are pissed for that reason. This license has been proven to be safe in several lawsuits. Just look at this page for example: http://gpl-violations.org/

Also, you omitted the actually interesting part of this paragraph:

> You may use our Services only as permitted by law, including applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.

As long as it's okay with your local jurisdiction, there's probably no problem in using NewPipe. E.g., for Germany, there is AFAIK no law that would prohibit any kind of usage that is possible with NewPipe, also, the download features are totally safe for personal use (so called "Privatkopie").

YouTube is also a big company backed by a huge company (Alphabet), and they make sure things are all right usually. Geoblocking etc. cannot be bypassed by using NewPipe, without a user's action of setting up Orbot. Also, they have contracts with GEMA, all big music brands, TV stations etc., to make sure the material on their site is licensed properly. The already mentioned Privatkopie is thus totally legal, the creation of it (the download process) and also the usage are legal, as the material has been licensed for the users by YouTube. Thus, watching in NewPipe is totally safe, as the data is still streamed from YouTube's servers.

Furthermore, NewPipe is not the only software that actually uses Google's services in the background. For example, startpage.com use Google as a "backend", but act as some kind of proxy to protect the users' privacy. They claim that their service is not illegal, and they actually _provide_ the service, so they _could_ be liable if their use of the Google search violated the ToS or any law.

A little story about something that was a lot more relevant years ago. On the internet, it's always been the uploaders that have been sued and punished, not the downloaders ("leechers"). All these torrent users have been sued for re-sharing the copyrighted material just because they weren't careful enough (they didn't deactivate their torrent clients' upload features and many of them have fallen for fake offerings and were captured this way, which only worked due to some grey zone the legislature left open in their laws).

So, in my opinion, it should be safe, and Google is really careful about punishing the actual users of their service. I don't think they'd sue any of their users for any reason, and who else could sue you otherwise? No one, at least in sane jurisdictions. You probably don't have to worry.
