### ISSUE TITLE
The Turkish video title has been translated into English

### ISSUE THREAD

**Issue by Qaz-7** [TeamNewPipe/NewPipeExtractor#1035]
Select Azerbaijan as the region.The title of this video is displayed in English on the trending page.It displays correctly in the player.Video titles should be extracted as is.
NewPipe

![Screenshot_20230305-000507_NewPipe](https://user-images.githubusercontent.com/124310688/222926983-8a43b6ec-8837-4dcc-aa2c-2fed1e375c10.jpg)

Player

![Screenshot_20230305-000528_NewPipe](https://user-images.githubusercontent.com/124310688/222927009-0cc27972-f71b-41ab-9fa6-ff1a1bf8b487.jpg)

YouTube
![Screenshot_20230305-001053_ReVanced Extended](https://user-images.githubusercontent.com/124310688/222926970-b48ec1d5-c3ce-4bc1-99d2-38293d072a31.jpg)

**Comment by AudricV** [comment]
This is a result of parsing YouTube only in English. Important and difficult changes are required to support YouTube in other languages on the extractor.

Original titles of videos are extracted when watching them since #857. There is no way to extract the original title in other places, as YouTube doesn't return this information (the only place I saw the ability to saw the original title was on search on a video title which was probably translated by Google Translate and not present on the watch page of the video).
