### ISSUE TITLE
[Question] best praxis when working on the NewPipeExtractor

### ISSUE THREAD

**Issue by MaX-Lo** [TeamNewPipe/NewPipeExtractor#129]
I'm trying to run the latest version of Newpipe dev branch with the latest version of the extractor (91b1efc97e) as described in https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/. Unfortunately the build fails because `Subtitles` and `SubtitlesFormat` can't be found.

So for me it seems that the Newpipe version is just not up to date with the latest extractor version yet. So my question is, whats the best praxis when trying to make changes/improve the extractor? Use the last working version?

**Comment by theScrabi** [comment]
That is a good question, well seems the last merge broke more then expected. Normally you should use the latest version, since this is the one that will eventually be supported by the app. However at the moment we have some trouble because, as you noticed the changes made in the extractor are not yet made in the frontend.
The coresponding PR in frontend can be found here: https://github.com/TeamNewPipe/NewPipe/pull/1759
