### ISSUE TITLE
Bandcamp Support

### ISSUE THREAD

**Issue by woorst** [TeamNewPipe/NewPipeExtractor#138]
An extractor for [bandcamp](https://bandcamp.com) would be awesome.

**Comment by theScrabi** [comment]
Well we would need someone who will write support for it ;)

**Comment by woorst** [comment]
I'm willing to take a crack at it if I could get pointed in the right direction.

**Comment by theScrabi** [comment]
You can take a look at the documentation: https://teamnewpipe.github.io/documentation/

**Comment by fynngodau** [comment]
@woorst Have you since made any progress in this regard? I, too, am interested in implementing bandcamp support. So far, I have already developed a [standalone Android client for bandcamp][bcd].

[bcd]: https://notabug.org/fynngodau/bandcampDirect

**Comment by fynngodau** [comment]
Anyhow, I have started implementing bandcamp support in [my fork][fork].

[fork]: https://github.com/fynngodau/NewPipeExtractor

**Comment by theScrabi** [comment]
Nice :) good luck

**Comment by fynngodau** [comment]
Here's a status report after working on it very intensively today and yesterday:

* Search works
* Multiple search pages get loaded correctly
* Search suggestions work (though bandcamp suggests results instead of autocompletions that once clicked in NewPipe aren't always the first result anymore)
* Streams work
 Descriptions are suboptimal because their newlines get eaten and then lyrics are really difficult to read
* Channels work, but don't display playlists (albums) because they can't #227
 I'm assuming all items on a channel to be on the first "page" because I don't know a profile where that is different. Uses the mobile api.
* Playlists work
 Playlists with a lot of streams take ages to load, because for every playlist info item, a separate request needs to be made to find out the URL of its cover. I believe this could be fixed on the client side, or worked around by pretending that all album's tracks have the same cover
* Two kiosks exist
   * `Featured`
   Currently only loads nine items currently can't load further "pages". Can contain preorder albums whose cover is not displayed correctly.
   * Bandcamp weekly (`Radio`)
    Works. Clicking uploader's (primary host's) name causes the crash reporter to open as it is a link to a fan page which is not implemented.
* Fan pages are not implemented. I don't know whether it's wanted to have them, I wouldn't mind not having them; they may be hard to distinguish from a musician's profile
* Unit tests exist but I'm assuming they are quite imperfect
* I had to add the `org.json` library because the website contains some JSON that has unquoted keys

**Comment by theScrabi** [comment]
Nice do you have a PR for us?

> Fan pages are not implemented. I don't know whether it's wanted to have them, I wouldn't mind not having them; they may be hard to distinguish from a musician's profile

I don't know. I don't use bandcamp. But if these are playlists like mixtapes, why not.

**Comment by fynngodau** [comment]
> Nice do you have a PR for us?

Sure, I can open one, though at the moment it's hard to use because a lot of tracks (streams) created by an artist (uploaded to a channel) are unreachable because they are part of an album (playlist) that can't be displayed inside the artist's profile (channel) as described in #227

> But if these are playlists like mixtapes, why not.

They are not, rather they would have to be represented as a channel. It's just all of the music somebody bought. One can "follow" fans on bandcamp and be followed by others, but I don't know whether anybody really uses this feature.
