### ISSUE TITLE
Can't play/download certain YouTube videos

### ISSUE THREAD

**Issue by Phoenix616** [TeamNewPipe/NewPipeExtractor#155]
Trying to play or download certain videos seems to be failing. They player just loads for a long time and the downloader fails with a 404 error.

The only video with this issue that I've encountered so far is this one: https://www.youtube.com/watch?v=jdELRPEbX4A

It seems to play fine on the website or official app but other third party players (noticed it in Kodi first) seem to fail too.

**Comment by theScrabi** [comment]
Noticed invideo.us has similar issues. Could you test if you can download the video using youtube-dl? Maybe they have a solution.

**Comment by omarroth** [comment]
Invidious will sometimes have issues with playback since users download the video from a different IP from where the video is requested. See omarroth/invidious#92, you should be able to fix this with `&local=true`.

I'm able to play/download the video linked in Invidious, youtube-dl, and NewPipe. I expect though the issue in this case is similar to fent/node-ytdl-core#417. To paraphrase: the video signature sometimes needs to be added as a different param name than `&signature=`.  See also ytdl-org/youtube-dl#18927.

[This line](https://github.com/TeamNewPipe/NewPipeExtractor/blob/560c648e92476cc220a036f1668c4335b98ceece/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L891) likely needs to be changed to something like:
```java
streamUrl = streamUrl + tags.get("sp") + decryptSignature(tags.get("s"), decryptionCode);
```

Similar to [this line](https://github.com/omarroth/invidious/blob/0.16.0/src/invidious/signatures.cr#L62) in Invidious.

**Comment by hp8wvvvgnj6asjm7** [comment]
Same here since two weeks.. please when do you release an update?

**Comment by TiA4f8R** [comment]
This issue should have been fixed (non-progressive/unavailable streams have been hidden since 0.20.0 and extraction of streams with `signatureCipher`s is handled properly), that's why I am closing this issue.

If that's not the case, please let us know.

Thank you!
