### ISSUE TITLE
Localization is not supported

### ISSUE THREAD

**Issue by mt131** [TeamNewPipe/NewPipeExtractor#375]
Localization is not supported ("Localization[en-GB]")
i had this error message when search

**Comment by TobiGr** [comment]
I cannot reproduce. Please give us more info: 

- Which service did you use?

- What's the exact error message?

**Comment by mt131** [comment]
set 
"shrinkResources true
minifyEnabled true"
in build grade make it happen when call 
extractor = YouTube.getSearchExtractor(query,
                            Collections.singletonList(YoutubeSearchQueryHandlerFactory.VIDEOS), "")

//////////

change to
"//shrinkResources true
minifyEnabled false"
and it is ok now

**Comment by wb9688** [comment]
Don't disable `minifyEnabled`, but add the following to your `proguard-rules.pro`:

```
-keep class org.schabi.newpipe.extractor.timeago.patterns.** { *; }
```

**Comment by TobiGr** [comment]
@wb9688 We might want to add that to the readme

**Comment by wb9688** [comment]
@TobiGr: Nah, the proper way is also generating an .aar (instead of only a .jar) and package that `proguard-rules.pro` in it, so apps don't have to manually include it. <sup>We should also clean up NewPipe's `proguard-rules.pro` as it contains a lot of rules that are now shipped with the libraries themselves in an .aar.</sup>
