### ISSUE TITLE
Port all invidio.us tests to other instances

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#381]
[invidio.us](https://invidio.us) will be shut down on 1st September. The API will be online for a few more days.
We need to port Invidious tests to another instance.

**Comment by bmanojkumar** [comment]
Hi @TobiGr , please guide me so that i can update the tests. I can see the test files at the locations `NewPipeExtractor/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/invidious/`
`NewPipeExtractor/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/InvidiousInstanceTest.java`
also i observed `https://invidio.us` instance in the files, let me know to which instance it should be updated. Thank you

**Comment by B0pol** [comment]
It's not needed, we only use invidio.us in a way to open links, we don't use the API yet
