### ISSUE TITLE
New m.soundcloud links are not accepted

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#399]
While testing a PR, I found out that 
https://soundcloud.com/liltecca/lil-tecca-dolly-feat-lil-uzi-vert-2
is accepted, but
https://m.soundcloud.com/liltecca/lil-tecca-dolly-feat-lil-uzi-vert-2
is not accepted.
https://github.com/TeamNewPipe/NewPipeExtractor/blob/6633f26ec5a73a8e932de575b7a0643b6ad6c890/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/linkHandler/SoundcloudStreamLinkHandlerFactory.java#L11-L12
needs to be modified

**Comment by wb9688** [comment]
It is accepted just fine… but it throws a ContentNotAvailableException somewhere for some reason.

**Comment by Scrxtchy** [comment]
I'm going to have to do a good rewrite of the rules used for URL processing. This is due to the widget (used for fetching IDs) not supporting the `www` and `m` domains

https://w.soundcloud.com/player/?url=https%3A%2F%2Fwww.soundcloud.com%2Fliltecca%2Flil-tecca-dolly-feat-lil-uzi-vert-2
https://w.soundcloud.com/player/?url=https%3A%2F%2Fm.soundcloud.com%2Fliltecca%2Flil-tecca-dolly-feat-lil-uzi-vert-2
https://w.soundcloud.com/player/?url=https%3A%2F%2Fsoundcloud.com%2Fliltecca%2Flil-tecca-dolly-feat-lil-uzi-vert-2

while work on 6a70cb9d50132c1cf1bf59478f029b199d65fefc and 538f5d3973258cc1b2943e0e4ccc9caf169a4c32 has appeared to be acceptable, it does appear I will in the future need to extract out the rules to it's on function to be applied to whatever linkhander's are appropriate to it

**Comment by Scrxtchy** [comment]
I gave this a second look, noticing how the comment originally posted was not reflective of what really was going on.
It's throwing the content not accepted due to it returning a HLS stream, which are not supported (#273)

I'm not sure what the situation is between me and the OP, but even the main site track is returning the same error, as both transcodings returned from the extractor are using hls, it's not something that is explicitly affecting the mobile domain

Testing tracks by other artists did not cause this error to be triggered when using the m subdomain.

**Comment by ShareASmile** [comment]
Does #526 cover this issue also along with #273 ?

**Comment by TiA4f8R** [comment]
Yes, my PR fixes extraction of this track.
Both mobile URL and desktop URL work.

@TobiGr Can I close this issue or is the bug still present for some other links and tracks?
