### ISSUE TITLE
Other services

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipeExtractor#4]
Is this code already ready for adding other services? If so, could I start implementing some other services?

**Comment by theScrabi** [comment]
I've never tried it. Would be interesting to see if it works.
For the beginning I recommend to use [np-cli](https://github.com/TeamNewPipe/np-cli). It might be less bitchy about such changes than the Android UI.

**Comment by wb9688** [comment]
OK! Btw can `np-cli` be built from the command line?

**Comment by theScrabi** [comment]
yes/no it should be easy to build it from commandline ... even without a make tool (I think) but I've never tried that :P

**Comment by wb9688** [comment]
OK, why aren't we using eg. Gradle? Btw what should I do with naming? Not
every service calls an user a channel like YouTube does.

**Comment by theScrabi** [comment]
Hm I schould create an empty teamplate service, so It's understandable for other people how services work.

If a service has users, use the channel anyway (but naming is a problem, you are right). Maybe we should rename tha channel class esecially.

However, if your service does not support channel/user return null. The frontend is required to understand what is possible with which service an dwhich is not (however NP Gui can not handle that so far.

**Comment by wb9688** [comment]
There are services that need both a channel ID and a stream ID for a
stream, how should I write the `UrlIdHandler` for them? Currently
`UrlIdHandler` only supports passing one `String`.

**Comment by wb9688** [comment]
OK, I totally forgot about this, since I didn't have much time. I've started working on a SoundCloud service, since I'm familiar with it. I've only done searching and streams (as they're called in NewPipe, in SoundCloud they're called tracks). I've also started working on a TUI, so I could test it. It looks like [this](https://i.imgur.com/vC9idbK.gifv). When I'm finished, I'll make a PR.

**Comment by TheAssassin** [comment]
*Offtopic:* I *love* that TUI you built. Old-ish user interface for modern internet technology.

**Comment by wb9688** [comment]
I've continued working on my SoundCloud service (and my NewPipe TUI) and I only have to implement playlists (as they're called in NewPipe, or sets as they're called on SoundCloud). [Here](https://i.imgur.com/W0h4uGL.gifv) is an updated gifv of it. Btw do we already have ideas for NewPipe's GUI?

**Comment by TheAssassin** [comment]
@wb9688 if you are annoyed by the different nomenclature, why not add a virtual function to the Playlist etc. interfaces called `identifier` (or some better name) which has to be implemented by the implementations? That'd make the interface feel a bit more "service native".

**Comment by wb9688** [comment]
@TheAssassin: Hmm… I think I'll first just finish my SoundCloud service
with the current interface and when it's merged I'll take a look at how I
could make NewPipeExtractor better for use with other services.

**Comment by TheAssassin** [comment]
Sure, I just did something similar recently for [libdesktopenvironments](https://github.com/TheAssassin/libdesktopenvironments/blob/c1b096394c52419015107e2eefe04fb410e92e5b/include/desktopenvironments.h#L42-L43), so I was reminded of that by your comment.

**Comment by TobiGr** [comment]
@wb9688 It's a great idea to add SoundCloud to NewPipe! Thank's for your work.
> Btw do we already have ideas for NewPipe's GUI? I was thinking about something like [this](https://i.imgur.com/CbAfzsC.gifv).

Since tabs will be introduced with TeamNewPipe/NewPipe#620 soon, another bar on the top of the screen doesn't seem to be a good solution to me. I thought a little about this problem and found two possible solutions:

1. **Refactor the search filter menu:** remove the old list and add clickable items. This gives the user the possibility to search for things in Youtube _and_ SoundCloud at the same time.
![search](https://user-images.githubusercontent.com/17365767/28756762-0727cb00-7575-11e7-88d8-34ad76bb44ad.jpg)
First sketch: default search bar Second sketch: Search bar after clicking on the filter icon (maybe the filter icon should not disappear to be accessible for further actions). The clickable items should have different background colors depending on their state.

2. **Add navigation drawer to app:** replace the old menu in the app bar by a navigation drawer. This solution gives the app a more modern look and separates all services.
![design](https://user-images.githubusercontent.com/17365767/28756763-072e3a80-7575-11e7-809c-e655a608861c.jpg)

Nevertheless @theScrabi's and @mauriciocolli's opinion on this topic would be pretty interesting.
Btw. should we move the discussion on the design to TeamNewPipe/NewPipe#78 ?

**Comment by wb9688** [comment]
@TobiasG: I didn't know about that PR. I think I'd prefer option 2, but I'd
also be interested in their opinion. I think discussion about NewPipe's
design should indeed not happen in this NewPipeExtractor repo. I think
we'll also need a design for a decent control activity for NewPipe's music
player. And we'll also need to think about what we'll do with audio-only
streams in the stream activity. For example the popup player wouldn't make
sense.

**Comment by wb9688** [comment]
Can this be closed or will this be used to also discuss other services?

**Comment by theScrabi** [comment]
@TobiGr I moved your commend [here](https://github.com/TeamNewPipe/NewPipe/issues/650). So we can continue the discussion there.
