### ISSUE TITLE
FR youtube-dl

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipeExtractor#466]
Due to how hard it is to watch videos in the app right now. CAPTCHA and stuff. I'd like to present an option to switch the entire app to using local youtube-dl instead of the extractor. Similar to FreeTubeApp/FreeTube#34

**Comment by Stypox** [comment]
Thank you for the proposal, though this is probably out of scope for NewPipe. Also, if by "local" you mean "self-hosted", then such a youtube-dl server would face the same issues NewPipe faces, since it would operate on the same exact network. We will support using invidious as a backend in the future, though, which could potentially solve the problems you face. You can look for the relevant PRs ;-)

**Comment by kubo6472** [comment]
In fact, invidious may solve this too. Through termux I was able to test ydl and true, YT was spitting 429 errors all over the place.
