### ISSUE TITLE
More services to support please

### ISSUE THREAD

**Issue by jefferson018200306** [TeamNewPipe/NewPipeExtractor#616]
may these services be supported in the near future. So audiophiles can enjoy different quality of music from different music streaming services. TIA!

TIDAL
Apple Music
Deezer
Amazon Music
Spotify
YouTube Music

**Comment by TiA4f8R** [comment]
This will be not possible for all services excepted YouTube Music because the others are using DRMs and requires for each an account in order to have a full access to the service, especially streaming URLs.

For YouTube Music, check this issue in the app repository: TeamNewPipe/NewPipe#4844.

I hope you will understand what I said. Closing this issue.
