### ISSUE TITLE
Are Mocks for tests useful?

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipeExtractor#634]
Now that the youtube tests have been running with the mock setup for more than 4 months, I wanted to ask if it served the purpose of improving the review process by making the CI suite more reliable.

What I myself observed is:
1. __It is only hiding the problem, not solving them__: CI is passing and the badge is green on the landing page 🎉 [![Build Status](https://github.com/TeamNewPipe/NewPipeExtractor/workflows/CI/badge.svg?branch=dev&event=push)](https://github.com/TeamNewPipe/NewPipeExtractor/actions), but if you take a look at the nightly scheduled runs which test against the real website, you see that it hasn't run successfully since more than 3 months.
2. Adding to that the only reason that it's passing, is because tests were ignored aggressivly. This can be done without this setup.
3. __Big overhead of mock generation__: Whenever you change someting in the youtube extractors, you have to regenerate the mocks. If you have a PR open and resolve some review, you have to regenerate them __again__. If you are on windows, tough life, some tests won't run on your system, because of file encoding. So you can't record them and need to use WSL to record them. Even tougher life if the video is blocked in your country.
4. __First time contributor hostile__: If you are new to the project, you won't know that there is such a system. Part of the problems is missing documentation on my part, but even with better document I find the barrier to entry raised unnecessarily. See #628 #629 

From this I personally would scrap the idea and go back to before.   
The setup itself can be kept to allow for tests which are impossible to run against the real website, like upcoming livestreams.

Thoughts? @TobiGr @Stypox

**Comment by TobiGr** [comment]
I'd rather keep the mocks for the following reasons:
1. Offline work. Create the tests and mocks once and work on the implementation after that.
1. When running all YouTube tests, we often run into reChaptcha challanges. That cannot happen with mocks.
1. Faster testing. Loading the requests from the disk is way faster than making requests to some servers. Running all tests with mock downloader takes the CI 2:15 minutes. The last nightly tests ran for 3:45. When working on a local machine the speedup is even higher. 
2. Making hundreds of requests to servers in a very short amount of time puts unnecessary load on the services' infrastructure. I was about to suggest to generate mocks for all services.
3. It is easier to see if a PR breakes certain stuff, because the mock tests should not fail.

I suggest to add a proper documentation to the readme and link to it in the PR template.

> It is only hiding the problem, not solving them: CI is passing and the badge is green on the landing page

Here you have a badge that is only for the sheduled workflows on dev: [![CI](https://github.com/TeamNewPipe/NewPipeExtractor/actions/workflows/ci.yml/badge.svg?branch=dev&event=schedule)](https://github.com/TeamNewPipe/NewPipeExtractor/actions/workflows/ci.yml)

**Comment by XiangRongLin** [comment]
I guess it is here to stay then
