### ISSUE TITLE
Channel has no videos, likes end up parsed

### ISSUE THREAD

**Issue by mauriciocolli** [TeamNewPipe/NewPipeExtractor#64]
Basically: the extractor is parsing everything that the `/videos` contains, this implies in:

- When the user has no uploads but has their likes public:
<img src="https://user-images.githubusercontent.com/13389907/35767210-0be57c9e-08cf-11e8-92ba-a535be3d8240.PNG" width="280">

- When the user has uploads and their likes public, the uploads is the default:
<img src="https://user-images.githubusercontent.com/13389907/35767220-29dbe094-08cf-11e8-87ed-54382d68dfe7.PNG" width="280">

- When neither is available:

<img src="https://user-images.githubusercontent.com/13389907/35767238-b887f364-08cf-11e8-9aed-f6f28d7cf58b.PNG" width="550">
 

Related issue TeamNewPipe/NewPipe#1066.

**Comment by AudricV** [comment]
This doesn't seem to be relevant anymore with the interface changes of YouTube interface and the setting of YouTube likes private since the 5th-6th of December 2019 (see the value `LL<channelID>` of the `Pattern` column of https://wiki.archiveteam.org/index.php/YouTube/Technical_details#Playlists and https://support.google.com/youtube/answer/6336092?hl=en).

Closing as outdated.
