### ISSUE TITLE
Why do you close a bug report for your APK?

### ISSUE THREAD

**Issue by cahd7** [TeamNewPipe/NewPipeExtractor#641]
they should be more considerate of users and resolve APK bugs instead of ignoring them and closing their reports as if they were fixed when they haven't received any response.

**Comment by opusforlife2** [comment]
Oh. I just saw you posted the same issue twice, and one was closed, so I closed the other one as well, thinking it was a double post.

The reason your first issue was closed is because this is the wrong repo. You need to open an issue in https://github.com/TeamNewPipe/NewPipe/issues. This is the repo for the Extractor, which is used by Newpipe, but also by other apps.

When you open an issue there, you'll see a template to follow that'll make it easier for us to understand your problem. Please fill it diligently.

Sorry about the confusion!
