### ISSUE TITLE
add tiktok

### ISSUE THREAD

**Issue by mhmmd10** [TeamNewPipe/NewPipeExtractor#695]
Hi
Add tik tok + Download video all quality +download without watermark

**Comment by gardenappl** [comment]
I might work on this, just for fun. Though this doesn't seem worth it, since Tiktok locks a lot of features (like reading comments) behind a login.

**Comment by TheAssassin** [comment]
I don't think that this is a very useful feature. TikTok has had a history of algorithms discriminating e.g., queer or political topics, massive issues with youth protection (with lawsuits in the UK and EU being brought to court), non-transparent political advertisement, generally issues with covert advertising, data protection issues (also because it is a Chinese product, and we all know that no company there can promise *any* data protection on par with EU legislation). There's been that weird "deal vs. no deal" story in the US. Their apps have had severe security and data protection issues in the past (e.g., reading clipboard information).

There is generally a lot of doubt with regards to them not blocking children under the age of 13 (which I think is pretty arbitrary) who, as a German blog put it, ["grow up in front of an audience of millions"](https://netzpolitik.org/2021/kinder-als-influencerinnen-aufwachsen-vor-millionenpublikum/).

German data protection agencies criticized last year that there is no effective data protection oversight within the EU. Like any company, they tried to set up their EU company in Ireland. The Irish DPA however tried to prevent them from doing so, as they are already busy with tons of other cases for big tech companies. Note that they had the chance to go anywhere. Running for Ireland is not a good move...

Some articles on netzpolitik.org have been released in English as well, e.g., https://netzpolitik.org/2019/cheerfulness-and-censorship/. Very worthwhile reading.

Please stop adding new proprietary services like these. TikTok seems a way worse idea than e.g., YouTube or SoundCloud. Instead, we should focus on providing good clients for free, open-source solutions.

**Comment by gardenappl** [comment]
I'm not a fan of TikTok either, but a bunch of my friends (and generally a lot of people my age) are into it. I was thinking this could help influence them to use NewPipe, and at the very least avoid proprietary clients, if not proprietary services.

**Comment by TheAssassin** [comment]
That's not a very convincing argument. First, I have doubts that any of these friends would be willing to use NewPipe (only). Most users of TikTok do want to participate

**Comment by gardenappl** [comment]
I think you're be right.

Also, I did spend a couple of hours writing a TikTok extractor, but having to test it with real data and watch actual content, I'm now convinced that TikTok is just stupid. NewPipe does not need it at all.

In case anybody still wants to look at the code: https://github.com/gardenappl/NewPipeExtractor/tree/tiktok-sucks (there really isn't much of it)

**Comment by opusforlife2** [comment]
Closing as rejected.

**Comment by theScrabi** [comment]
@TheAssassin I need TikTok. And the generation that uses it just started to study IT. So in other words it's just a matter of time when there will be the first opensource app available that allows tik tok to be watched watcht.

**Comment by selurvedu** [comment]
FYI there's an alternative frontend for TikTok here <https://github.com/pablouser1/ProxiTok>

**Comment by rugk** [comment]
It has been some time since the issue had been closed and people keep sending me tiktok links. It seems to stay a popular platform especially for younger (_Gen Z_) people, so yeah…
So I'd ask to reconsider this.

While I would not support the platform I agree I would love NewPipe integration, so I do not have to use that pesky website. 
Its like YouTube, you also don't want to use YouTube that is why you use NewPipe, you just cannot or only partially can influence what websites other people use.

Just playing videos would be enough for me/initially IMHO.

**Comment by rugk** [comment]
Well an Android app would be more convenient on your phone, but I agree on desktops that is likely a good thing.
