### ISSUE TITLE
[YouTube] Couldn't get high quality thumbnails

### ISSUE THREAD

**Issue by fuzhengyin** [TeamNewPipe/NewPipeExtractor#763]
server response
<img width="1138" alt="截屏2021-12-13 下午2 25 23" src="https://user-images.githubusercontent.com/89236842/145762845-71d2a175-96b9-4da8-b2eb-d78b82a26390.png">

**Comment by fuzhengyin** [comment]
The last one is `https://i.ytimg.com/vi_webp/tUKfStEXf7Y/maxresdefault.webp`, and not accessible

**Comment by fuzhengyin** [comment]
Is API old?
`public static final String YOUTUBEI_V1_URL = "https://www.youtube.com/youtubei/v1/";`
Should use v3

**Comment by fuzhengyin** [comment]
video id is `tUKfStEXf7Y `

**Comment by TiA4f8R** [comment]
> Is API old?
> `public static final String YOUTUBEI_V1_URL = "https://www.youtube.com/youtubei/v1/";`
> Should use v3

No, you are mixing YouTube's official API (that we can't use) and YouTube's internal API (that we are using).

We are right now always using the latest thumbnail of the thumbnails array: see the following code:

https://github.com/TeamNewPipe/NewPipeExtractor/blob/1dc80957d8c21f14b2186a6a1b7b456e717fd51d/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L268-L271

Getting all thumbnails would require to return a list of images instead of only an image. See #268 (which should be at least partially used or rebased/reused, in my opinion) for an example of implementation.

**Comment by AudricV** [comment]
@fuzhengyin I'm working on providing multiple images support on the extractor. In your case, this means that you will get in the future every thumbnail that YouTube returns on avatars, channel banners and video and playlist thumbnails.
