### ISSUE TITLE
Add support for Rumble

### ISSUE THREAD

**Issue by harmin-parra** [TeamNewPipe/NewPipeExtractor#779]
Add support for Rumble

[https://github.com/TeamNewPipe/NewPipe/issues/6645](https://github.com/TeamNewPipe/NewPipe/issues/6645)

[Rumble and Odysee #736](https://github.com/TeamNewPipe/NewPipeExtractor/issues/736)

**Comment by twitchplaystrading** [comment]
The original devs find free speech offensive, sorry. But here's a forked one with Bitchute and Rumble: [https://github.com/bravenewpipe/NewPipe](url)

**Comment by opusforlife2** [comment]
Rumble supports misinformation, unfortunately: https://www.wired.com/story/rumble-sends-viewers-tumbling-toward-misinformation/

So this service request has to be rejected. If this changes in the future, we could reconsider.

**Comment by EvanCarroll** [comment]
@opusforlife2 For reason to reconsider, I'm a Trump-hating leftist and lot of respectable people are on Rumble too. YouTube hosts Glenn Beck, Fox News, Ben Shapiro, and Bret Weinstein which you'd probably agree all perpetuate "misinformation." Aside from that, the dominant opinion on is one which is anti-working class pro-war and pro-Israel if for no other reason then because everything prioritized is big six news, https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw

* https://rumble.com/c/GGreenwald https://en.wikipedia.org/wiki/Glenn_Greenwald

**Comment by opusforlife2** [comment]
It's not about specific people. It's about the general trend.

**Comment by EvanCarroll** [comment]
That response wasn't about a specific person. If we're judging by content or the owner's material interest, the general trend is that YouTube is anti-working class, pro-status quo, pro-war, pro-intervention, pro-imperialism, pro-colonization, and pro-Zionist and basically part of a large transnational corporation that's embedded in the state, and one which openly does its bidding. And not just one state [but many](https://en.wikipedia.org/wiki/Censorship_of_YouTube). Going so far as to regionally bow the censors of multiple states, often times for political reasons.

Rumble like YouTube is another 3 B corporation. I'm sure there are lots of bad content you can find there. But what's the general trend of Rumble? It sounds like it splits profit more equitably and is less inclined to remove content (on both sides as I don't care at all about the right-wing stuff on it). That is to say, it sounds like a lesser evil.

Does "general trend" apply to PeerTube too? What if trends right, or towards "misinformation"? Certainly a lot of the alt-right is heavily invested in decentralized nonsense too.

**Comment by opusforlife2** [comment]
Reply to 1st and 2nd paras: If _that's_ the scale of influence you're considering, then just using a different app or platform won't solve the problem you've stated (deep state). You'd need to build a grassroots movement and bring a political revolution in your country,state, or area, at the very least.

Scaling it down by a lot, if you just focus on one person being exposed to information on both platforms, the idea is that they would be more likely to be harmed (or harm others) based on the misinformation they receive on Rumble or another alt-right platform, than on Youtube. It's not about the larger, vaguer questions of which political/economic/social system is better, but about simpler, more direct things like not letting people die because they or their parents/guardians were misinformed about vaccines.

> Going so far as to regionally bow the censors of multiple states, often times for political reasons.

That is not a Youtube problem, it is a large-company problem. Any company with a user base that is significant enough to be noticed by a government will see similar interference. Again, the solution to such a problem is political, not technological, in that governments should be prevented from engaging in such interference. Otherwise we'd all constantly be looking for the next promising small platform each time the current one becomes too big.

Also, there is a need to be more grounded when discussing these things. The problems with the "general trend" you've stated are very USA-centric, and so are things like alt-right platforms. None of this applies to Youtube users in Asia or Africa, for example. They account for more than 3/4th of the global population.

Reply to 3rd para: The nature of how decentralised services work is the very antidote to all this. You're not exposed to all the content of the platform as a whole, but only bits and pieces that you choose, and you can easily avoid misinformation by not federating with the wrong servers. There is no "it" to trend right or left at all.

**Comment by EvanCarroll** [comment]
> You'd need to build a grassroots movement and bring a political revolution in your country,state, or area, at the very least.

I agree! Fully! I don't think the burden though should be on me to defend against that claim. If that's your position (and mine) how is not doing that but instead stopping me and others from consuming anti-war content making a difference? I think you're arguing a point I would make, but the conclusion is inconsistent. If the only salvation is a grass roots movement and political revolution why are we concerned with the state's definition of "misinformation" or protecting the largest most state-embedded content hosting platform? Or whatever else which certainly doesn't entail revolution but ended up in patches getting rejected.

> more likely to be harmed (or harm others) based on the misinformation they receive on Rumble or another alt-right platform, than on Youtube

While I agree with your first point, as a foundation. I don't get this one. If we're talking about an aggregate effect, you're more likely to be harmed and harm others with viewing YouTube then simply _not_ viewing YouTube. Do you actually believe the mass media is a force of good in the world. There has to be some subjective value you place on desirable content rather than aggregate effect of hosting. Where is the voice on YouTube that is pushing for a negotiated settlement in Ukraine, or not merely fighting until the last dead Ukrainian? Where is the voice in the MSM pushing for ending the US arms to Saudi Arabia? Or an end to colonization in Palestine? Or speaking up right now against the a future US invasion of Haiti?

> simpler, more direct things like not letting people die because they or their parents/guardians were misinformed about vaccines.

Revisit your first point, you're not going to change American's understanding of science by blocking Rumble. That requires education (albeit not social revolution). Moreover, as someone who is double vaxed and now triple boosted there are _plenty_ of reasons to welcome vaccine skepticism. It's a nuanced subject. You're not saving the world by stopping ignorant people from trying to grapple as adults with the facts of COVID, vaccine development, and efficacy. You're merely pushing them into their churches and temples where they were perfectly fine and successful at breathing, eating, sleeping, and breeding ignorantly for the past 3,000 years with union busting, snake-kissing, chick tract reading, white supremacist, pray-the-gay-away sweat rooms like they did before YouTube.

> None of this applies to Youtube users in Asia or Africa, for example. They account for more than 3/4th of the global population.

I'm not sure where you're talking about, specifically. In what country on those two continents would access to Rumble produce worse effects then access to YouTube? I don't understand this scenario. But because you're talking about such a high amount population, presumably India and China are center? China censors both. So it's moot. Enabling Rumble access in app would have no effect there. India censors YouTube and YouTube censors for India. And when that fails [India just turns off the internet for everyone.](https://rumble.com/vdf2gt-india-cuts-internet-farmers-start-hunger-strike.html) In what case are we theorizing Rumble would have a negative effect outside of the first-world?

> You're not exposed to all the content of the platform as a whole, but only bits and pieces that you choose, and you can easily avoid misinformation by not federating with the wrong servers. There is no "it" to trend right or left at all.

Let's recap,

* **I want to be exposed to _some_ content on $x**
* **I do NOT want to be exposed to _some_ content on $x**

The same is true for any value of $x. The problem here is that when $x is Rumble, you're telling me because **YOU** can not control what content I am exposed to, you will not allow me to subscribe to content providers; that your moral calculations are superior to my moral calculations. Why would that be any different on _any_ other platform decentralized or not? If a user wants to subscribe to a decentralized federated alt-right Inforwars server, are you going to stop them? Fundamentally what's the difference if the service is decentralized and they "subscribe" to Infowars as an alt-right content provider that hosts a federated server, or they subscribe by ringing a bell on Rumble? It seems everywhere you're arguing not that you should push for a grass roots revolution, but that you should have control/discretion to engineer a platform that takes a stance as to what bells get ringed on the basis of your understanding of science and disposition.

To that I'm just providing balance: you're locking people into YouTube which is the most successful, profitable, and blatant propaganda tool of our American empire. And I just want to watch banned personalities cover the anti-war effect, and update me on Assange's extradition.

**Comment by opusforlife2** [comment]
> instead stopping me and others from consuming anti-war content making a difference

Let's be clear. That is not happening at all. No one has the power to stop you from doing anything of the sort.

> why are we concerned with the state's definition of "misinformation" or protecting the largest most state-embedded content hosting platform

We are not concerned with this at all. This is just a FOSS app to access some media services. Nothing more, nothing less.

> you're more likely to be harmed and harm others with viewing YouTube then simply not viewing YouTube

Absolutely. Which is why it is great that users have the freedom of not installing Newpipe, or even installing it but never using it to access Youtube.

Regarding the rest of the post: all these points are irrelevant to a simple service addition request to an app. We're not a political platform, and our doing or not doing something is hardly going to make any impact in the world.

The question occurred to me upon reading your comment: Are you not aware of [Bravenewpipe](https://github.com/bravenewpipe/NewPipe)? Or are you pushing for Rumble inclusion in the upstream app for other reasons?

**Comment by EvanCarroll** [comment]
None of that is consistent with what actually happened. There are actual patches released under the same license [here](https://github.com/TeamNewPipe/NewPipe/compare/dev...bravenewpipe:NewPipe:dev).The reason why those patches are **NOT** accepted is ideological. That's what this ticket is about, you said that much,

> Rumble supports misinformation, unfortunately

And,

> parents/guardians were misinformed about vaccines.

You think it's the job of NewPipe to decide what kind of content I can access, if you deem it to be undesirable you reject patches. **That is happening**. Otherwise this would be open, those patches would be reviewed, and there would be only technical barriers for inclusion, rather than barriers placed on content providers or networks to moderate content to your personal whims.

> Are you not aware of [Bravenewpipe](https://github.com/bravenewpipe/NewPipe)? Or are you pushing for Rumble inclusion in the upstream app for other reasons?

**It's not on me.** You're really missing here any reasonable understanding of [burden of proof](https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)). It's your job to tell people as a maintainer of an open source project why a patch isn't acceptable. Not for others to tell you why they'd rather not use a fork. In this case you're defining your position based on your personal evaluation of the content and your desire to stop others from consuming content you find disagreeable.

Of course there are reasons why I don't want to use a fork. They should be _extremely_ obvious.

* I am a long time user of NewPipe, and I trust the quality of software and the maintenance of it.
* [bravenewpipe](https://github.com/bravenewpipe) is 243 commits behind
* It's [not on f-droid](https://search.f-droid.org/?q=braven&lang=en), so I place less trust in the build
* I don't want to build my own presonal apks.
* I don't expect Open Source App developers to moderate the content I choose to view.

**Comment by opusforlife2** [comment]
> You think it's the job of NewPipe to decide what kind of content I can access

> your desire to stop others from consuming content you find disagreeable

Nope. Again, Newpipe cannot stop you from accessing Rumble if you want it. And the team is powerless to stop people from doing anything.

> It's not on me.

> It's your job 

It's not on anyone. There is no "job". This is a FOSS app made by volunteers. There is no burden on anyone to do anything. We're not deciding anything for you. If you disagree with the decisions made by the team, the license grants you full freedom to modify the source code for your purposes.

In this case, the task is made much easier because there is already an existing fork with fully working Rumble support, that only needs to be updated to keep up with upstream.

---

There is nothing stopping you from using Bravenewpipe only for Rumble and staying with Newpipe for the rest of the services.

**Comment by FromRightToLeft** [comment]
> Rumble supports misinformation, unfortunately: https://www.wired.com/story/rumble-sends-viewers-tumbling-toward-misinformation/
> 
> So this service request has to be rejected. If this changes in the future, we could reconsider.

I don't want to start a political debate. I will only point that fact-checkers have been proven wrong, and many things deemed as “misinformation” were later proven to be true. 

You call upon the fact that it is FOSS which I find strange in the light of your actions. What happened with Stallman’s: „Free as free speech”? Even if people are wrong don’t they have a right to be, and don’t I have the right to use my own judgement?

This whole thing is antithetical to FOSS philosophy. You cannot limit and steer software development based on your political feelings. FOSS was meant to bring us together as a community and not divide as. People shouldn’t feel like they need a fork for political reasons and create Bravenewpipe.

**Comment by opusforlife2** [comment]
But that is exactly what's beautiful about how the FOSS community works. If you don't like something, you can always fork and make your own decisions. No one has the power to stop you from doing anything.

**Comment by FromRightToLeft** [comment]
But you omitted the core of my argument, so let me spell it for you: I argue that politics is a wrong reason to force people to fork. What say you?

**Comment by Seanld** [comment]
Denying contributions based on political opinion may end up fracturing the development of NewPipe. I envision: one version has some cool features, the other one does as well, but they cannot combine due to codebase differences, and won't due to political differences. Now we're stuck with two separately-inferior versions.

The contributions are there, all you have to do is merge them. But apparently the users are too juvenile to decide what content they want to subscribe to, even though the majority of people using NewPipe are already probably fairly critically-thinking, if they've jumped ship from the mainline applications.

Just because forking is an _option_, doesn't make it the _optimal option_. Keeping everyone working on one project to spite the spyware-ridden, bloated, closed-source default apps is something we should be united on. But I guess we're not capable of achieving that.
