### ISSUE TITLE
[FEATURE] deactivated features on community guideline critical videos

### ISSUE THREAD

**Issue by FlorianSteenbuck** [TeamNewPipe/NewPipeExtractor#82]
Youtube decides to deactivate Features on community guideline critical Videos.
Currently I only see it on this video "https://www.youtube.com/watch?v=6iMuMKjaU4w", but I also see videos of rappers that get in similar mode "https://www.youtube.com/watch?v=p-BfaQQxuO4".

The problem we got with the first video is that we could not get the channel url (which is deactivated by Youtube). Also we could not get the next Video. And we could not get the uploader thumbnail url.

I would be better to get a log system and only throw an error if we detecting that the video is not an community guidline critical video.

**Comment by theScrabi** [comment]
Someone hat to write a fix, so we can suppport these videos without errors.

**Comment by AudricV** [comment]
This issue doesn't seem to be present anymore: on the only video which is available among the ones provided `p-BfaQQxuO4` (the other has been removed due to violation of YouTube's TOS), I can get the uploader name, URL and avatar URL.

Not being able to extract uploader info is not considered critical in `StreamInfo` objects: only [stream's name, URL, ID and age limit are required](https://github.com/TeamNewPipe/NewPipeExtractor/blob/d961d349c35c93c53ae419935d93fa4533fe71ca/extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfo.java#L119-L125).

Requirement of getting video info metadata of YouTube streams has been removed in #968.

Closing the issue as fixed.
