### ISSUE TITLE
Inappropriate download speed 

### ISSUE THREAD

**Issue by 0Karakurt0** [TeamNewPipe/NewPipeExtractor#885]
When using any speed greater than 1x, New Pipe seems to be underestimating required speed for continuous stream. Sometimes it is as bad as 100 kb/s for 1440p video, or even not loading at all, being stuck at some kind of conversation with 50 kb/s bandwidth.
I have little to none idea in how to diagnose this, so feel free to ask for anything required.

**Comment by AudricV** [comment]
First of all, your issue is not opened in the good repository (you are in the extractor repository and not in the app repository).

If you are talking about YouTube, the issue should have been fixed with 0.23.1, as we are now using DASH instead of progressive HTTP to play YT contents (and that's what I personally recommend to do to get better loading speeds in clients, except on legacy streams in which it can create issues).

The download speed is not within our control but in the control of ExoPlayer, the player library we use. Such speeds seem to be Google video server throttling or some throttling on the network you use, and ExoPlayer does not throttle downloads at all, but uses only a single download thread if I am not wrong.

Closing as invalid.
