### ISSUE TITLE
VideoStream content length < 0

### ISSUE THREAD

**Issue by nikitoSha** [TeamNewPipe/NewPipeExtractor#918]
Hi.
Thanks for the best lib!
I had a some problems with checking file size. For example: I get video streams and try to `videoStream.getItagItem().getContentLength()`. It works, but for 720p it always = -1. Time to time I see the same situation with 480p of video. Do you know the reason of value = "-1" (getContentLength)?
Sorry for my English :)

**Comment by AudricV** [comment]
`-1` means that the value is unknown (see the `CONTENT_LENGTH_UNKNOWN` constant of the `ItagItem` class), and so not extracted because it is not returned by YouTube.

> It works, but for 720p it always = -1

Is it the itag 22? If so, YouTube doesn't return this information for legacy video streams (video streams with audio), you will have to get it using a HEAD request.

> Time to time I see the same situation with 480p of video.

Could you share video IDs on which you get this behavior?

Also, remember that this stream model is temporary and `ItagItem`s will be reworked in the future.

**Comment by nikitoSha** [comment]
Okay, I send you info tomorrow from office

**Comment by nikitoSha** [comment]
Hi. Sorry for late answer. Example:
[https://m.youtube.com/watch?v=odP7SD6fCNQ](url)

VideoStream of 360p:
![Screenshot_199](https://user-images.githubusercontent.com/15741303/187656992-3fdd26c3-3bf2-4e62-9a9f-6f956709ecd5.png)

**Comment by AudricV** [comment]
I should have said this, but legacy video streams also include itags 17 and 18, so that's intended.
